trigger:
- main

variables:
  dockerRegistryServiceConnection: 'monitoringacr'  # Replace with your actual service connection name
  imageRepository: 'health-api'
  containerRegistry: 'monitoringacr01.azurecr.io'       # e.g., brendaacr.azurecr.io
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  gitCommit: '$(Build.SourceVersion)'
  releaseId: '$(Build.BuildId)'  # Use Build ID here since Release stage is in YAML now

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push to ACR'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: Docker@2
      displayName: 'Build and Push Docker image'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
          latest
        arguments: |
          --build-arg GIT_COMMIT=$(gitCommit) --build-arg RELEASE_ID=$(releaseId)

- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: Build
  jobs:
  - job: DeployToAKS
    displayName: 'kubectl apply deployment.yaml'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Kubernetes@1
      displayName: 'Deploy to AKS'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'aks0sc'  # ⚠️ Not subscription name
        azureResourceGroup: 'aks-rg'
        kubernetesCluster: 'aks01'
        command: apply
        useConfigurationFile: true
        configuration: 'deployment.yaml'
