trigger:
- master

variables:
  dockerRegistryServiceConnection: 'monitorsc'
  imageRepository: 'health-api'
  containerRegistry: 'monitoringacr01.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

  # Variables passed to container
  BUILD_VERSION: 'v$(Build.BuildId)'
  GIT_COMMIT: '$(Build.SourceVersion)'
  RELEASE_ID: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push to ACR'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: Docker@2
      displayName: 'Build and Push Docker image'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: buildAndPush
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)

- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: Build
  jobs:
  - job: DeployToAKS
    displayName: 'Generate Deployment and Apply'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: PowerShell@2
      displayName: 'Transform deployment.yaml in-place'
      env:
        BUILD_VERSION: $(BUILD_VERSION)
        GIT_COMMIT: $(GIT_COMMIT)
        RELEASE_ID: $(RELEASE_ID)
      inputs:
        targetType: 'inline'
        script: |
          $filePath = "$(System.DefaultWorkingDirectory)/deployment.yaml"
          $content = Get-Content $filePath -Raw

          # Define a script block that replaces $(VARIABLE) with its env value
          $updatedContent = [regex]::Replace($content, '\$\((\w+)\)', {
            param($match)
            $envVar = $match.Groups[1].Value
            $value = (Get-Item "Env:$envVar").Value
            if (-not $value) {
              Write-Host "⚠️  Environment variable '$envVar' is not set. Replacing with 'undefined'."
              return "undefined"
            }
            Write-Host "✅ Replacing $($match.Value) with '$value'"
            return $value
          })

          # Write the transformed YAML back to file
          Set-Content -Path $filePath -Value $updatedContent -Force



    - task: Kubernetes@1
      displayName: 'Deploy to AKS'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'aks0sc'
        azureResourceGroup: 'aks-rg'
        kubernetesCluster: 'aks01'
        command: apply
        useConfigurationFile: true
        configuration: 'deployment.yaml'
