apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-api
  template:
    metadata:
      labels:
        app: health-api
    spec:
      containers:
      - name: health-api
        image: monitoringacr01.azurecr.io/health-api:$(Build.BuildId)
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: BUILD_VERSION
          value: "$(BUILD_VERSION)"
        - name: GIT_COMMIT
          value: "$(GIT_COMMIT)"
        - name: RELEASE_ID
          value: "$(RELEASE_ID)"
---
apiVersion: v1
kind: Service
metadata:
  name: health-api-service
spec:
  selector:
    app: health-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
